# Generated by Django 3.2.9 on 2021-12-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('przedmiot', models.CharField(choices=[('informatyka', 'Informatyka'), ('grafika', 'Grafika'), ('matematyka', 'Matematyka'), ('malarstwo', 'Malarstwo'), ('muzyka', 'Muzyka'), ('angielski', 'J.angielski')], max_length=20)),
                ('PESEL', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('tytul_naukowy', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przedmiot', models.CharField(choices=[('informatyka', 'Informatyka'), ('grafika', 'Grafika'), ('matematyka', 'Matematyka'), ('malarstwo', 'Malarstwo'), ('muzyka', 'Muzyka'), ('angielski', 'J.angielski')], max_length=20)),
                ('grupa', models.IntegerField()),
                ('miejsca', models.IntegerField()),
                ('ilosc_godzin', models.IntegerField()),
                ('sylabus', models.TextField()),
                ('id_instruktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetonApp.instruktor')),
            ],
        ),
        migrations.CreateModel(
            name='Kursant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zakupu', models.DateField()),
                ('id_instruktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetonApp.instruktor')),
                ('id_kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetonApp.kurs')),
            ],
        ),
    ]
