# Generated by Django 3.2.9 on 2021-12-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zetonApp', '0002_auto_20211210_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeton',
            name='id_instruktor',
        ),
        migrations.AddField(
            model_name='zeton',
            name='id_kursant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zetonApp.kursant', verbose_name='kursant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zeton',
            name='data_zakupu',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zeton',
            name='id_kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetonApp.kurs', verbose_name='kurs'),
        ),
    ]
