# Generated by Django 3.2.9 on 2022-01-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zetonApp', '0003_auto_20211229_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='id_instruktor',
        ),
        migrations.RemoveField(
            model_name='zeton',
            name='id_kurs',
        ),
        migrations.RemoveField(
            model_name='zeton',
            name='id_kursant',
        ),
        migrations.AddField(
            model_name='kurs',
            name='instruktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kursy', to='zetonApp.instruktor'),
        ),
        migrations.AddField(
            model_name='zeton',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapisani', to='zetonApp.kurs', verbose_name='kurs'),
        ),
        migrations.AddField(
            model_name='zeton',
            name='kursant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zetony', to='zetonApp.kursant', verbose_name='kursant'),
        ),
    ]
