# Generated by Django 3.2.9 on 2022-01-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zetonApp', '0004_auto_20220121_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='sylabus',
            new_name='nazwa',
        ),
    ]
