# Generated by Django 3.2.9 on 2022-01-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetonApp', '0005_rename_sylabus_kurs_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeton',
            name='data_zakupu',
            field=models.DateField(auto_now_add=True),
        ),
    ]
